import { AppError, codes, createLogger, sleep, type Logger } from '@cs2coach/shared';
import type { FaceitCs2Stats, FaceitMatchDetail, FaceitPlayerHistory, FaceitPlayerCore, FaceitPlayerSearchResponse, FaceitMatchStats } from './types';
export type FetchBody = string | URLSearchParams | null;
interface CacheEntry { expiresAt: number; value: unknown; }
class TtlCache { private map = new Map<string, CacheEntry>(); get(key:string):unknown|undefined{const e=this.map.get(key);if(!e)return undefined;if(e.expiresAt<Date.now()){this.map.delete(key);return undefined;}return e.value;} set(key:string,value:unknown,ttlMs:number):void{this.map.set(key,{expiresAt:Date.now()+ttlMs,value});if(this.map.size>500){const k=this.map.keys().next().value as string|undefined;if(k)this.map.delete(k);}} }
export interface FaceitApiClientOptions { apiKey?:string;baseUrl?:string;timeoutMs?:number;maxRetries?:number;cacheTtlMs?:number;logger?:Logger; }
const RETRYABLE_STATUS=new Set([429,500,502,503,504]);
export class FaceitApiClient {
 private readonly apiKey?:string; private readonly baseUrl:string; private readonly timeoutMs:number; private readonly maxRetries:number; private readonly cacheTtlMs:number; private readonly logger:Logger; private readonly cache=new TtlCache();
 constructor(opts:FaceitApiClientOptions){this.apiKey=opts.apiKey;this.baseUrl=opts.baseUrl??'https://open.faceit.com/data/v4';this.timeoutMs=opts.timeoutMs??10000;this.maxRetries=opts.maxRetries??2;this.cacheTtlMs=opts.cacheTtlMs??60000;this.logger=opts.logger??createLogger('faceit-client');}
 hasApiKey():boolean{return Boolean(this.apiKey);} private cacheKey(method:string,path:string,query?:URLSearchParams):string{return `${method} ${path}?${query?.toString()??''}`;}
 async get<T>(path:string,query?:Record<string,string|number|undefined>,opts?:{ttlMs?:number}):Promise<T>{return this.request<T>('GET',path,{query,ttlMs:opts?.ttlMs});}
 async post<T>(path:string,body?:URLSearchParams|object,authBearer?:string):Promise<T>{return this.request<T>('POST',path,{body,authBearer});}
 private async request<T>(method:'GET'|'POST',path:string,ctx:{query?:Record<string,string|number|undefined>;body?:URLSearchParams|object;authBearer?:string;ttlMs?:number}):Promise<T>{
  if(!this.apiKey&&!ctx.authBearer)throw new AppError(codes.missingEnv,'FACEIT_API_KEY is not configured',500);const base=this.baseUrl.endsWith('/')?this.baseUrl:`${this.baseUrl}/`;const url=new URL(path.replace(/^\/+/,''),base);if(ctx.query)for(const[k,v]of Object.entries(ctx.query))if(v!==undefined)url.searchParams.set(k,String(v));if(method==='GET'){const c=this.cache.get(this.cacheKey(method,url.toString()));if(c!==undefined)return c as T;}
  const headers:Record<string,string>={Accept:'application/json','User-Agent':'cs2-ai-coach/0.1'};if(ctx.authBearer)headers.Authorization=`Bearer ${ctx.authBearer}`;else if(this.apiKey)headers.Authorization=`Bearer ${this.apiKey}`;let bodyData:FetchBody|undefined;if(ctx.body){if(ctx.body instanceof URLSearchParams){headers['Content-Type']='application/x-www-form-urlencoded';bodyData=ctx.body;}else{headers['Content-Type']='application/json';bodyData=JSON.stringify(ctx.body);}}
  let lastError:unknown;for(let attempt=0;attempt<=this.maxRetries;attempt++){const started=Date.now();try{const res=await this.rawFetch(url.toString(),{method,headers,body:bodyData});const duration=Date.now()-started;if(res.status===429){const ms=this.parseRetryAfter(res.headers.get('retry-after'),1000);this.logger.warn('faceit_rate_limited',{path,attempt,retryAfterMs:ms});await sleep(Math.min(ms,15000));if(attempt<this.maxRetries)continue;throw new AppError(codes.rateLimited,'FACEIT rate limit exceeded',429);}if(RETRYABLE_STATUS.has(res.status)){const delay=Math.min(500*2**attempt,4000);this.logger.warn('faceit_retry',{path,status:res.status,attempt,duration});if(attempt<this.maxRetries){await sleep(delay);continue;}throw new AppError(codes.upstreamError,`FACEIT returned ${res.status}`,503);}const text=await res.text();if(res.status>=400){this.logger.warn('faceit_error',{path,status:res.status,duration,upstreamBody:text.slice(0,500)});throw new AppError(this.mapStatus(res.status),`FACEIT ${method} ${path} failed (${res.status})`,res.status);}const parsed=text?(JSON.parse(text)as T):(undefined as unknown as T);if(method==='GET')this.cache.set(this.cacheKey(method,url.toString()),parsed,ctx.ttlMs??this.cacheTtlMs);return parsed;}catch(err){lastError=err;if(err instanceof AppError)throw err;const timeoutish=err instanceof Error&&err.name==='TimeoutError';const delay=Math.min(500*2**attempt,4000);this.logger.warn('faceit_network_error',{path,attempt,error:timeoutish?'timeout':err instanceof Error?err.message:String(err)});if(attempt<this.maxRetries){await sleep(delay);continue;}throw new AppError(timeoutish?codes.upstreamTimeout:codes.upstreamError,timeoutish?'FACEIT request timed out':'FACEIT upstream error',timeoutish?504:503,lastError instanceof Error?{cause:lastError.message}:undefined);}}
  throw new AppError(codes.upstreamError,'FACEIT upstream error',503,lastError instanceof Error?{cause:lastError.message}:undefined);
 }
 private async rawFetch(url:string,init:{method:string;headers:Record<string,string>;body?:FetchBody}):Promise<Response>{const c=new AbortController();const t=setTimeout(()=>c.abort(),this.timeoutMs);try{return await fetch(url,{...init,signal:c.signal});}finally{clearTimeout(t);}}
 private parseRetryAfter(v:string|null,fallbackMs:number):number{if(!v)return fallbackMs;const s=Number.parseInt(v,10);if(Number.isFinite(s))return s*1000;const d=Date.parse(v);return Number.isFinite(d)?Math.max(0,d-Date.now()):fallbackMs;}
 private mapStatus(s:number):string{if(s===401)return'FACEIT_UNAUTHORIZED';if(s===403)return'FACEIT_FORBIDDEN';if(s===404)return'FACEIT_NOT_FOUND';return'FACEIT_ERROR';}
 getPlayerByNickname(nickname:string,game='cs2'):Promise<FaceitPlayerCore>{return this.get('/players',{nickname,game});}
 getPlayerByGamePlayerId(gamePlayerId:string,game='cs2'):Promise<FaceitPlayerCore>{return this.get('/players',{game_player_id:gamePlayerId,game},{ttlMs:5*60000});}
 searchPlayers(nickname:string,game='cs2'):Promise<FaceitPlayerSearchResponse>{return this.get('/search/players',{nickname,game,limit:20});}
 getPlayerById(playerId:string,opts?:{ttlMs?:number}):Promise<FaceitPlayerCore>{if(!playerId)throw new AppError(codes.badRequest,'FACEIT player id is missing',400);return this.get(`/players/${encodeURIComponent(playerId)}`,undefined,opts);}
 async resolvePlayer(playerId:string|undefined|null,nickname?:string,game='cs2'):Promise<FaceitPlayerCore>{let lastError:unknown; if(playerId){try{return await this.getPlayerById(playerId,{ttlMs:0});}catch(error){lastError=error;}} if(nickname){try{return await this.getPlayerByNickname(nickname,game);}catch(error){lastError=error;try{const r=await this.searchPlayers(nickname,game);const exact=r.items.find(i=>i.nickname.toLowerCase()===nickname.toLowerCase());const item=exact??r.items[0];if(item)return{player_id:item.player_id,nickname:item.nickname,avatar:item.avatar,country:item.country,games:{}};}catch(searchError){lastError=searchError;}}} if(lastError instanceof Error)throw lastError;throw new AppError(codes.badRequest,'FACEIT player id or nickname is required',400);}
 async getPlayerMatches(playerId:string,input:{offset?:number;limit?:number}={}):Promise<FaceitPlayerHistory>{return this.get(`/players/${encodeURIComponent(playerId)}/history`,{game:'cs2',offset:input.offset??0,limit:input.limit??20},{ttlMs:15000});}
 async getMatchById(matchId:string):Promise<FaceitMatchDetail>{return this.get(`/matches/${encodeURIComponent(matchId)}`,undefined,{ttlMs:30000});}
 async getMatchStats(matchId:string):Promise<FaceitMatchStats>{return this.get(`/matches/${encodeURIComponent(matchId)}/stats`,undefined,{ttlMs:0});}
 async getPlayerStats(playerId:string,game='cs2'):Promise<FaceitCs2Stats>{return this.get(`/players/${encodeURIComponent(playerId)}/stats/${encodeURIComponent(game)}`);}
}