import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { navigate } from '../App';
import type { PostMatchAnalysis } from '../lib/types';
interface Props { faceitMatchId:string; }
export default function PostMatch({faceitMatchId}:Props){
 const [analysis,setAnalysis]=useState<PostMatchAnalysis|null>(null),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{try{setAnalysis(await api.getMatchAnalysis(faceitMatchId));setError(null)}catch(err){setError((err as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[faceitMatchId]);
 const generate=async()=>{if(generating)return;setGenerating(true);setError(null);try{setAnalysis(await api.generateMatchAnalysis(faceitMatchId))}catch(err){setError((err as Error).message)}finally{setGenerating(false)}};
 if(loading)return <main className="panel command-center"><header className="command-topbar"><div className="brand-lockup"><div className="brand-mark">C</div><div><strong>CS2<span>COACH</span></strong><small>AI ANALYSIS</small></div></div><button className="back" onClick={()=>navigate('matches')}>‹</button></header><div className="waiting-card"><div className="spinner"/><h2>ANALYZING MATCH…</h2><p className="muted">Round data va performance signallari olinmoqda.</p></div></main>;
 return <main className="panel command-center"><header className="command-topbar"><div className="brand-lockup"><div className="brand-mark">C</div><div><strong>CS2<span>COACH</span></strong><small>POST-MATCH INTELLIGENCE</small></div></div><button className="back" onClick={()=>navigate('matches')}>‹</button></header>{error&&<p className="error-banner">{error}</p>}
 {!analysis?<section className="hero-card disconnected-hero"><div className="hero-grid"/><div className="hero-copy"><span className="eyebrow">MATCH COMPLETE</span><h1>TURN DATA<br/><em>INTO SKILL.</em></h1><p>AI tahlil roundlar, qarorlar va mavjud match signallari asosida sizga eng katta improvement nuqtalarini chiqaradi.</p><button className="primary hero-cta" onClick={()=>void generate()} disabled={generating}>{generating?'AI ANALYZING…':'GENERATE AI ANALYSIS  →'}</button></div></section>:<>
 <section className="card analysis-hero"><span className="eyebrow">PERFORMANCE SCORE</span><div className="analysis-big"><strong>{Math.round(Object.values(analysis.overallScore).reduce((a,b)=>a+b,0)/8)}</strong><small>/100</small></div><span className="elo-delta">{analysis.source==='groq'?'AI MODEL ANALYSIS':'RULE-BASED ANALYSIS'}</span></section>
 <section className="card"><div className="section-heading"><div><span className="eyebrow">SKILL BREAKDOWN</span><h2>Performance</h2></div></div><div className="score-grid">{Object.entries(analysis.overallScore).map(([key,value])=><div className="score-item" key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{value}</strong></div>)}</div></section>
 <section className="card"><span className="eyebrow">ROUND REVIEW</span><div className="analysis-block"><b>BEST ROUND</b><p>{analysis.bestRound?`#${analysis.bestRound.roundNumber} — ${analysis.bestRound.reason}`:'Yetarli maʼlumot yo‘q'}</p></div><div className="analysis-block"><b>WORST ROUND</b><p>{analysis.worstRound?`#${analysis.worstRound.roundNumber} — ${analysis.worstRound.reason}`:'Yetarli maʼlumot yo‘q'}</p></div></section>
 <section className="card"><span className="eyebrow">AI INSIGHTS</span><h2>Biggest mistakes</h2><ul>{analysis.topMistakes.map((x,i)=><li key={i}>{x}</li>)}</ul><h2>Good decisions</h2><ul>{analysis.topDecisions.map((x,i)=><li key={i}>{x}</li>)}</ul></section>
 <section className="card"><span className="eyebrow">OPPONENT MODEL</span><h2>Patterns</h2><ul>{analysis.opponentPatterns.length?analysis.opponentPatterns.map((x,i)=><li key={i}>{x}</li>):<li>Pattern hali yetarli emas.</li>}</ul></section>
 <section className="card"><span className="eyebrow">PERSONAL DEVELOPMENT</span><h2>7-day training plan</h2><div className="analysis-list">{analysis.trainingPlan.map(day=><div className="analysis-row" key={day.day}><span>DAY {day.day}</span><b>{day.focus}</b></div>)}</div></section><button className="secondary" onClick={()=>void generate()} disabled={generating}>{generating?'AI ANALYZING…':'↻ REGENERATE ANALYSIS'}</button></>}
 <nav className="bottom-nav"><button onClick={()=>navigate('home')}><span>⌂</span><small>Home</small></button><button onClick={()=>navigate('matches')}><span>◫</span><small>Matches</small></button><button className="active"><span>◈</span><small>Analysis</small></button><button onClick={()=>navigate('home')}><span>◎</span><small>Profile</small></button></nav></main>;
}
