import type { Language } from './i18n';

type Key = 'hero'|'enter'|'analysis'|'syncing'|'avatar'|'player'|'level'|'match'|'matchError'|'loadingError'|'statusLive'|'statusReady'|'statusStarting'|'statusFinished'|'statusScheduled'|'history'|'webhookWaiting'|'demo'|'waitingLive'|'coachNeedsMatch'|'analysing'|'confidenceHigh'|'confidenceMedium'|'confidenceLow'|'confidence'|'ai'|'rules'|'signal'|'collecting'|'liveWebSocket'|'fallbackPolling'|'round'|'loginAgain'|'splashFoot'|'alive';
const text:Record<Language,Record<Key,string>>={
 uz:{hero:'FACEIT matchlaringiz uchun real vaqt taktik murabbiy. O‘yin holati aniq qarorlarga aylanadi.',enter:'KIRISH →',analysis:'TAHLIL',syncing:'SINXRONLANMOQDA…',avatar:'FACEIT avatari',player:'O‘yinchi',level:'DARAJA',match:'MATCH',matchError:'Match xatosi',loadingError:'Yuklash xatosi',statusLive:'JONLI',statusReady:'TAYYOR',statusStarting:'BOSHLANMOQDA',statusFinished:'YAKUNLANDI',statusScheduled:'REJALASHTIRILGAN',history:'TARIX',webhookWaiting:'FACEIT webhook va CS2 GSI keyingi o‘yinni kutmoqda.',demo:'DEMO REJIMI — ishlab chiqish uchun simulyatsiya qilingan oqim',waitingLive:'Jonli o‘yin ma’lumotlari kutilmoqda',coachNeedsMatch:'Murabbiy maslahat berishi uchun haqiqiy davom etayotgan match kerak. Simulyatsiya qilingan ma’lumot ko‘rsatilmaydi.',analysing:'Round tahlil qilinmoqda…',confidenceHigh:'Yuqori',confidenceMedium:'O‘rta',confidenceLow:'Past',confidence:'ishonch',ai:'AI',rules:'qoidalar',signal:'signal',collecting:'yig‘ilmoqda…',liveWebSocket:'WebSocket orqali jonli',fallbackPolling:'zaxira tekshiruv',round:'round',loginAgain:'QAYTA KIRISH →',splashFoot:'HAQIQIY TAHLIL · HAQIQIY RIVOJLANISH',alive:'tirik'},
 ru:{hero:'Тактический тренер в реальном времени для ваших матчей FACEIT. Состояние игры превращается в конкретные решения.',enter:'ВОЙТИ →',analysis:'АНАЛИЗ',syncing:'СИНХРОНИЗАЦИЯ…',avatar:'Аватар FACEIT',player:'Игрок',level:'УР.',match:'МАТЧ',matchError:'Ошибка матча',loadingError:'Ошибка загрузки',statusLive:'ТЕКУЩИЙ',statusReady:'ГОТОВ',statusStarting:'ЗАПУСКАЕТСЯ',statusFinished:'ЗАВЕРШЁН',statusScheduled:'ЗАПЛАНИРОВАН',history:'ИСТОРИЯ',webhookWaiting:'Ожидаем следующий матч через FACEIT webhook и CS2 GSI.',demo:'ДЕМО-РЕЖИМ — поток симулируется для разработки',waitingLive:'Ожидание данных текущей игры',coachNeedsMatch:'Тренеру нужен настоящий запущенный матч, чтобы давать советы. Симулированные данные не показываются.',analysing:'Анализ раунда…',confidenceHigh:'Высокая',confidenceMedium:'Средняя',confidenceLow:'Низкая',confidence:'уверенность',ai:'AI',rules:'правила',signal:'сигнал',collecting:'собираем…',liveWebSocket:'в реальном времени через WebSocket',fallbackPolling:'резервная проверка',round:'раунд',loginAgain:'ВОЙТИ СНОВА →',splashFoot:'РЕАЛЬНЫЙ АНАЛИЗ · РЕАЛЬНЫЙ ПРОГРЕСС',alive:'живы'},
 en:{hero:'Real-time tactical coaching for your FACEIT matches. Your game state becomes actionable decisions.',enter:'ENTER →',analysis:'ANALYSIS',syncing:'SYNCING…',avatar:'FACEIT avatar',player:'Player',level:'LVL',match:'MATCH',matchError:'Match error',loadingError:'Loading error',statusLive:'LIVE',statusReady:'READY',statusStarting:'STARTING',statusFinished:'FINISHED',statusScheduled:'SCHEDULED',history:'HISTORY',webhookWaiting:'Waiting for the next match through FACEIT webhook and CS2 GSI.',demo:'DEMO MODE — simulated stream for development',waitingLive:'Waiting for live game data',coachNeedsMatch:'The coach needs a real, running match to give advice. No simulated data is shown.',analysing:'Analysing the round…',confidenceHigh:'High',confidenceMedium:'Medium',confidenceLow:'Low',confidence:'confidence',ai:'AI',rules:'rules',signal:'signal',collecting:'collecting…',liveWebSocket:'live via WebSocket',fallbackPolling:'fallback polling',round:'round',loginAgain:'LOG IN AGAIN →',splashFoot:'REAL INSIGHTS · REAL IMPROVEMENT',alive:'alive'}
};
export function ui(lang:Language,key:Key):string{return text[lang][key];}
