import type { Language } from './i18n';

/** Copy for the standalone website: landing, sign-in, settings, notifications. */
const text = {
  uz: {
    signIn: 'FACEIT ORQALI KIRISH',
    signInShort: 'Kirish',
    openDashboard: 'PANELGA O‘TISH →',
    howItWorks: 'Qanday ishlaydi',
    landingEyebrow: 'CS2 UCHUN AI TAKTIK MURABBIY',
    landingLead: 'FACEIT akkauntingiz bilan kiring. Match paytida jonli taktik maslahatlar, o‘yindan keyin AI tahlil va mashg‘ulot rejasi — hammasi bitta saytda.',
    secureNote: 'Parolingizni ko‘rmaymiz — kirish FACEIT’ning rasmiy OAuth sahifasi orqali.',
    f1Title: 'Jonli taktik chaqiruvlar',
    f1Body: 'Iqtisod, round holati va raqib odatlariga qarab har round uchun aniq qaror.',
    f2Title: 'Matchdan keyingi AI tahlil',
    f2Body: 'Kuchli va zaif tomonlaringiz, xatolar va shaxsiy mashg‘ulot rejasi.',
    f3Title: 'Telegram bildirishnomalari',
    f3Body: 'Match boshlanganda va tugaganda Telegram’ga qisqa xabar — bir tugma bilan saytga qaytasiz.',
    step1: 'FACEIT orqali kiring',
    step2: 'Odatdagidek match o‘ynang',
    step3: 'Jonli maslahat va tahlilni oling',
    footer: 'CS2USTOZ · Powered by JASCOAV',
    signingIn: 'Kirilmoqda…',
    signInFailed: 'Kirish amalga oshmadi',
    backHome: 'Bosh sahifaga',
    settings: 'Sozlamalar',
    account: 'AKKAUNT',
    signedInWith: 'FACEIT orqali kirilgan',
    logout: 'CHIQISH',
    notifications: 'BILDIRISHNOMALAR',
    telegramTitle: 'Telegram bildirishnomalari',
    telegramDesc: 'Match boshlanganda va tugaganda Telegram’ga xabar oling. Bot faqat bildirishnoma yuboradi.',
    connectTelegram: 'TELEGRAM’NI ULASH',
    waitingTelegram: 'Telegram’da botni oching va START tugmasini bosing…',
    telegramLinked: 'Ulangan',
    disconnectTelegram: 'Telegram’ni uzish',
    notificationsOn: 'Bildirishnomalar yoqilgan',
    notificationsOff: 'Bildirishnomalar o‘chirilgan',
    telegramUnavailable: 'Telegram bildirishnomalari hozircha serverda sozlanmagan.',
    alertsPromptTitle: 'Match xabarlarini oling',
    alertsPromptBody: 'Telegram’ni ulang — match boshlanganda va tugaganda xabar keladi.',
    alertsPromptCta: 'ULASH →',
    language: 'TIL',
  },
  ru: {
    signIn: 'ВОЙТИ ЧЕРЕЗ FACEIT',
    signInShort: 'Войти',
    openDashboard: 'ОТКРЫТЬ ПАНЕЛЬ →',
    howItWorks: 'Как это работает',
    landingEyebrow: 'AI-ТАКТИЧЕСКИЙ ТРЕНЕР ДЛЯ CS2',
    landingLead: 'Войдите через аккаунт FACEIT. Живые тактические подсказки во время матча, AI-разбор и план тренировок после игры — всё на одном сайте.',
    secureNote: 'Мы не видим ваш пароль — вход через официальную OAuth-страницу FACEIT.',
    f1Title: 'Живые тактические коллы',
    f1Body: 'Конкретное решение на каждый раунд с учётом экономики, ситуации и привычек соперника.',
    f2Title: 'AI-разбор после матча',
    f2Body: 'Сильные и слабые стороны, ошибки и персональный план тренировок.',
    f3Title: 'Уведомления в Telegram',
    f3Body: 'Короткое сообщение в Telegram о начале и конце матча — одна кнопка, и вы снова на сайте.',
    step1: 'Войдите через FACEIT',
    step2: 'Играйте матч как обычно',
    step3: 'Получайте подсказки и разбор',
    footer: 'CS2USTOZ · Powered by JASCOAV',
    signingIn: 'Выполняем вход…',
    signInFailed: 'Не удалось войти',
    backHome: 'На главную',
    settings: 'Настройки',
    account: 'АККАУНТ',
    signedInWith: 'Вход через FACEIT',
    logout: 'ВЫЙТИ',
    notifications: 'УВЕДОМЛЕНИЯ',
    telegramTitle: 'Уведомления в Telegram',
    telegramDesc: 'Получайте сообщение в Telegram о начале и конце матча. Бот только присылает уведомления.',
    connectTelegram: 'ПОДКЛЮЧИТЬ TELEGRAM',
    waitingTelegram: 'Откройте бота в Telegram и нажмите START…',
    telegramLinked: 'Подключено',
    disconnectTelegram: 'Отключить Telegram',
    notificationsOn: 'Уведомления включены',
    notificationsOff: 'Уведомления выключены',
    telegramUnavailable: 'Уведомления Telegram пока не настроены на сервере.',
    alertsPromptTitle: 'Получайте уведомления о матчах',
    alertsPromptBody: 'Подключите Telegram — сообщим о начале и конце матча.',
    alertsPromptCta: 'ПОДКЛЮЧИТЬ →',
    language: 'ЯЗЫК',
  },
  en: {
    signIn: 'SIGN IN WITH FACEIT',
    signInShort: 'Sign in',
    openDashboard: 'OPEN DASHBOARD →',
    howItWorks: 'How it works',
    landingEyebrow: 'AI TACTICAL COACH FOR CS2',
    landingLead: 'Sign in with your FACEIT account. Live tactical calls during the match, an AI review and a training plan afterwards — all on one website.',
    secureNote: 'We never see your password — sign-in happens on FACEIT’s official OAuth page.',
    f1Title: 'Live tactical calls',
    f1Body: 'A concrete decision every round based on economy, round state and opponent habits.',
    f2Title: 'Post-match AI review',
    f2Body: 'Strengths, weaknesses, mistakes and a personal training plan.',
    f3Title: 'Telegram alerts',
    f3Body: 'A short Telegram message when your match starts and ends — one tap brings you back to the site.',
    step1: 'Sign in with FACEIT',
    step2: 'Play your match as usual',
    step3: 'Get live calls and a review',
    footer: 'CS2USTOZ · Powered by JASCOAV',
    signingIn: 'Signing you in…',
    signInFailed: 'Sign-in failed',
    backHome: 'Back to home',
    settings: 'Settings',
    account: 'ACCOUNT',
    signedInWith: 'Signed in with FACEIT',
    logout: 'LOG OUT',
    notifications: 'NOTIFICATIONS',
    telegramTitle: 'Telegram notifications',
    telegramDesc: 'Get a Telegram message when your match starts and finishes. The bot only sends notifications.',
    connectTelegram: 'CONNECT TELEGRAM',
    waitingTelegram: 'Open the bot in Telegram and press START…',
    telegramLinked: 'Connected',
    disconnectTelegram: 'Disconnect Telegram',
    notificationsOn: 'Notifications on',
    notificationsOff: 'Notifications off',
    telegramUnavailable: 'Telegram notifications are not configured on the server yet.',
    alertsPromptTitle: 'Get match alerts',
    alertsPromptBody: 'Connect Telegram — we’ll message you when a match starts and ends.',
    alertsPromptCta: 'CONNECT →',
    language: 'LANGUAGE',
  },
} satisfies Record<Language, Record<string, string>>;

export type WebTextKey = keyof typeof text.en;

export function wt(lang: Language, key: WebTextKey): string {
  return text[lang][key];
}
